DROP TABLE IF EXISTS urls;

create table url (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  created_at                    timestamp not null,
);

DROP TABLE IF EXISTS url_checks;

create table url_check (
  id                            bigint generated by default as identity not null,
  status_code                   integer not null,
  title                         varchar(255),
  h1                            varchar(255),
  description                   clob,
  url_id                        bigint,
  created_at                    timestamp not null,
  url_id      bigint                                  not null
);
